# Generated by Django 2.1.5 on 2019-01-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='title_text',
        ),
    ]
