# Generated by Django 2.1.5 on 2019-01-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0002_auto_20190108_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
