# Generated by Django 2.1.5 on 2019-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0004_gallery_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload_time',
            field=models.DateField(auto_now=True),
        ),
    ]
