# Generated by Django 2.1.5 on 2019-01-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0005_auto_20190108_1606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('title_text', 'upload_time')},
        ),
    ]
